name = "flag-dataset"
main = "src/index.ts"
compatibility_date = "2022-11-18"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "flag-dataset-updated"
database_id = "734f3fb4-f25d-44fb-b6f6-ce72e26381fb"
